---

- name: Auto attach RHEL subscription
  tags: attach_subscription
  community.general.redhat_subscription:
    state: present
    username: "{{ rh_uid }}"
    password: "{{ rh_pass }}"
    auto_attach: yes
    force_register: yes