---
- name: Turn off SELinux temporarily
  tags: httpd
  command: setenforce 0

- name: httpd listen on port 8081
  tags: httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: "^Listen 80"
    line: "Listen 8081"
    state: present