---

- name: Check to see if qcow2 file already exists on KVM host
  tags: create_rhel_vm
  stat:
    path: /var/lib/libvirt/images/bastion_base.qcow2
  ignore_errors: yes
  register: qcow2_check

- name: Create working directory
  tags: create_rhel_vm
  file:
    path: /var/lib/libvirt/images/tmp/{{ web1_hostname }}
    state: directory
    mode: '0755'
  
- name: Create base image
  tags: create_rhel_vm
  command: "qemu-img create -b /var/lib/libvirt/images/bastion_base.qcow2 -f qcow2 /var/lib/libvirt/images/{{ web1_hostname }}.qcow2 {{ web1_disk }}G"
  register: qemu_create

- name: Get info about qemu image creation
  tags: create_rhel_vm
  command: "qemu-img info /var/lib/libvirt/images/{{ web1_hostname }}.qcow2"
  register: qemu_info

- name: Create instance-id
  tags: create_rhel_vm
  shell: "echo \"instance-id: $(uuidgen || echo i-abcdefg)\" > /var/lib/libvirt/images/tmp/{{ web1_hostname }}/meta-data"
  register: uuidgen
  
- name: Use cloud_init.cfg.j2 template to make user-data file
  tags: create_rhel_vm
  template:
    src: roles/create_rhel_vm/templates/cloud_init.cfg.j2
    dest: /var/lib/libvirt/images/tmp/{{ web1_hostname }}/user-data
  
- name: Use network_config_static.cfg.j2 template to make network-config file
  tags: create_rhel_vm
  template:
    src: roles/create_rhel_vm/templates/network_config_static.cfg.j2
    dest: /var/lib/libvirt/images/tmp/{{ web1_hostname }}/network-config

- name: Generate iso file
  tags: create_rhel_vm
  command: genisoimage -output /var/lib/libvirt/images/{{ web1_hostname }}-seed.img -volid cidata -joliet -rock /var/lib/libvirt/images/tmp/{{ web1_hostname }}/meta-data /var/lib/libvirt/images/tmp/{{ web1_hostname }}/network-config /var/lib/libvirt/images/tmp/{{ web1_hostname }}/user-data
  register: gen_iso
  
- name: Boot web server
  tags: create_rhel_vm
  command: virt-install 
    --name {{ web1_hostname }} \
    --virt-type kvm \
    --memory {{ web1_ram }} \
    --vcpus {{ web1_vcpu }} \
    --boot hd \
    --disk path=/var/lib/libvirt/images/{{ web1_hostname }}-seed.img,device=cdrom \
    --disk path=/var/lib/libvirt/images/{{ web1_hostname }}.qcow2,device=disk \
    --graphics none \
    --os-type Linux --os-variant rhel{{ web1_os_version }} \
    --network network=macvtap-net \
    --noautoconsole \
    --noreboot
  
- name: Restart web server
  tags: create_rhel_vm
  command: virsh start {{ web1_hostname }}

- name: Waiting 3 minutes for automated installation and configuration to complete. To monitor, use a web browser to go to https://your-kvm-host-ip-address-here:9090, sign in as 'root', then go to the 'Virtual Machines' tab and click on the hostname you'd like to see.
  tags: create_rhel_vm
  pause:
    minutes: 3
  

    
